//
//  DeveloperPreview.swift
//  bublic
//
//  Created by andrew austin on 10/25/23.
//

import Foundation

class DeveloperPreview {
    
    static let shared = DeveloperPreview()
    
    var workspaces: [Workspace] = [
        .init(
            id: NSUUID().uuidString,
            workspaceUid: NSUUID().uuidString,
            workspaceName: "Blacktip Co-Working",
            workspaceImageUrl: "blacktip-logo",
            fee: 5,
            latitude: 37.7749,
            longitude: -122.4194,
            imageURLs: ["blacktip-1", "blacktip-2", "blacktip-3"],
            address: "2/35 Moo 3",
            city: "Koh Tao",
            state: "Surattani",
            country: "Thailand",
            title: "Cozy Jungle Co-Working ",
            rating: 4.7,
            features: [.superWorker],
            amenities: [.wifi, .kitchen, .tv],
            type: .apartment
        ),
//        .init(
//            id: NSUUID().uuidString,
//            workspaceUid: NSUUID().uuidString,
//            ownerName: "Alice Smith",
//            ownerImageUrl: "alice_smith_image",
//            pricePerNight: 250,
//            latitude: 34.0522,
//            longitude: -118.2437,
//            imageURLs: ["listing-3", "listing-4","listing-1", "listing-2"],
//            address: "456 Oak St",
//            city: "Los Angeles",
//            state: "CA",
//            title: "Spacious Family Home",
//            rating: 4.9,
//            features: [.superHost],
//            amenities: [.wifi, .kitchen, .laundry, .tv, .alarmSystem],
//            type: .house
//        ),
////        .init(
//            id: NSUUID().uuidString,
//            ownerUid: NSUUID().uuidString,
//            ownerName: "Emily Johnson",
//            ownerImageUrl: "emily_johnson_image",
//            numberOfBedrooms: 1,
//            numberOfBathrooms: 1,
//            numberOfGuests: 2,
//            numberOfBeds: 1,
//            pricePerNight: 100,
//            latitude: 40.7128,
//            longitude: -74.0060,
//            imageURLs: ["listing-2", "listing-4","listing-1", "listing-2"],
//            address: "789 Elm St",
//            city: "New York",
//            state: "NY",
//            title: "Downtown Studio Apartment",
//            rating: 4.6,
//            features: [.selfCheckin],
//            amenities: [.wifi, .kitchen, .tv],
//            type: .apartment
//        ),
//        .init(
//            id: NSUUID().uuidString,
//            ownerUid: NSUUID().uuidString,
//            ownerName: "Michael Brown",
//            ownerImageUrl: "michael_brown_image",
//            numberOfBedrooms: 4,
//            numberOfBathrooms: 3,
//            numberOfGuests: 8,
//            numberOfBeds: 4,
//            pricePerNight: 350,
//            latitude: 41.8781,
//            longitude: -87.6298,
//            imageURLs: ["listing-4", "listing-3","listing-1", "listing-2"],
//            address: "101 Pine St",
//            city: "Chicago",
//            state: "IL",
//            title: "Luxury City Condo",
//            rating: 4.8,
//            features: [.superHost],
//            amenities: [.wifi, .kitchen, .laundry, .tv],
//            type: .apartment
//        ),
//        .init(
//            id: NSUUID().uuidString,
//            ownerUid: NSUUID().uuidString,
//            ownerName: "Sarah Wilson",
//            ownerImageUrl: "sarah_wilson_image",
//            numberOfBedrooms: 2,
//            numberOfBathrooms: 2,
//            numberOfGuests: 4,
//            numberOfBeds: 2,
//            pricePerNight: 180,
//            latitude: 33.7490,
//            longitude: -84.3880,
//            imageURLs: ["listing-2", "listing-4","listing-1", "listing-3"],
//            address: "567 Oak Lane",
//            city: "Atlanta",
//            state: "GA",
//            title: "Charming Townhouse",
//            rating: 4.7,
//            features: [.selfCheckin],
//            amenities: [.wifi, .kitchen, .laundry, .tv],
//            type: .townhouse
//        ),
//        .init(
//            id: NSUUID().uuidString,
//            ownerUid: NSUUID().uuidString,
//            ownerName: "David Clark",
//            ownerImageUrl: "david_clark_image",
//            numberOfBedrooms: 3,
//            numberOfBathrooms: 2,
//            numberOfGuests: 6,
//            numberOfBeds: 3,
//            pricePerNight: 280,
//            latitude: 32.7157,
//            longitude: -117.1611,
//            imageURLs: ["listing-4", "listing-3","listing-1", "listing-2"],
//            address: "789 Palm Blvd",
//            city: "San Diego",
//            state: "CA",
//            title: "Beachfront Getaway",
//            rating: 4.9,
//            features: [.superHost],
//            amenities: [.pool, .wifi, .kitchen, .laundry, .tv, .balcony],
//            type: .villa
//        ),
//        .init(
//            id: NSUUID().uuidString,
//            ownerUid: NSUUID().uuidString,
//            ownerName: "Linda Miller",
//            ownerImageUrl: "linda_miller_image",
//            numberOfBedrooms: 2,
//            numberOfBathrooms: 2,
//            numberOfGuests: 4,
//            numberOfBeds: 2,
//            pricePerNight: 160,
//            latitude: 47.6062,
//            longitude: -122.3321,
//            imageURLs: ["listing-2", "listing-4","listing-1", "listing-3"],
//            address: "456 Pine Ave",
//            city: "Seattle",
//            state: "WA",
//            title: "Modern Condo with a View",
//            rating: 4.8,
//            features: [.superHost],
//            amenities: [.wifi, .kitchen, .laundry, .tv],
//            type: .apartment
//        ),
//        .init(
//            id: NSUUID().uuidString,
//            ownerUid: NSUUID().uuidString,
//            ownerName: "James Lee",
//            ownerImageUrl: "james_lee_image",
//            numberOfBedrooms: 3,
//            numberOfBathrooms: 2,
//            numberOfGuests: 6,
//            numberOfBeds: 3,
//            pricePerNight: 220,
//            latitude: 29.7604,
//            longitude: -95.3698,
//            imageURLs: ["listing-1", "listing-4","listing-3", "listing-2"],
//            address: "101 Harbor Dr",
//            city: "Houston",
//            state: "TX",
//            title: "Spacious Riverside House",
//            rating: 4.7,
//            features: [.selfCheckin],
//            amenities: [.wifi, .kitchen, .laundry, .tv],
//            type: .house
//        )
    ]
}
